version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "david-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1v6wx3qmpfmza"
s3_prefix = "david-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
